config/routes.rb
ControleFinanceiro::Application.routes.draw do
  resources :sub_categorias

  resources :categorias

  resources :transacoes

  resources :contas

end

app/models/conta.rb
class Conta < ActiveRecord::Base
  attr_accessible :agencia, :descricao, :juros, :limite, :nome, :numero, :saldo, :tipo, :vencimento
end

app/controllers/contas_controller.rb
class ContasController < ApplicationController
  # GET /contas
  # GET /contas.json
  def index
    @contas = Conta.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contas }
    end
  end

  # GET /contas/1
  # GET /contas/1.json
  def show
    @conta = Conta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conta }
    end
  end

  # GET /contas/new
  # GET /contas/new.json
  def new
    @conta = Conta.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @conta }
    end
  end

  # GET /contas/1/edit
  def edit
    @conta = Conta.find(params[:id])
  end

  # POST /contas
  # POST /contas.json
  def create
    @conta = Conta.new(params[:conta])

    respond_to do |format|
      if @conta.save
        format.html { redirect_to @conta, notice: 'Conta was successfully created.' }
        format.json { render json: @conta, status: :created, location: @conta }
      else
        format.html { render action: "new" }
        format.json { render json: @conta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contas/1
  # PUT /contas/1.json
  def update
    @conta = Conta.find(params[:id])

    respond_to do |format|
      if @conta.update_attributes(params[:conta])
        format.html { redirect_to @conta, notice: 'Conta was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @conta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contas/1
  # DELETE /contas/1.json
  def destroy
    @conta = Conta.find(params[:id])
    @conta.destroy

    respond_to do |format|
      format.html { redirect_to contas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/views/contas/_form.html.erb
<%= form_for(@conta) do |f| %>
  <% if @conta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conta.errors.count, "error") %> prohibited this conta from being saved:</h2>

      <ul>
      <% @conta.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :numero %><br />
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :agencia %><br />
    <%= f.number_field :agencia %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :juros %><br />
    <%= f.text_field :juros %>
  </div>
  <div class="field">
    <%= f.label :saldo %><br />
    <%= f.text_field :saldo %>
  </div>
  <div class="field">
    <%= f.label :limite %><br />
    <%= f.text_field :limite %>
  </div>
  <div class="field">
    <%= f.label :vencimento %><br />
    <%= f.date_select :vencimento %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contas/edit.html.erb
<h1>Editing conta</h1>

<%= render 'form' %>

<%= link_to 'Show', @conta %> |
<%= link_to 'Back', contas_path %>

app/views/contas/index.html.erb
<h1>Listing contas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Numero</th>
    <th>Agencia</th>
    <th>Descricao</th>
    <th>Tipo</th>
    <th>Juros</th>
    <th>Saldo</th>
    <th>Limite</th>
    <th>Vencimento</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contas.each do |conta| %>
  <tr>
    <td><%= conta.nome %></td>
    <td><%= conta.numero %></td>
    <td><%= conta.agencia %></td>
    <td><%= conta.descricao %></td>
    <td><%= conta.tipo %></td>
    <td><%= conta.juros %></td>
    <td><%= conta.saldo %></td>
    <td><%= conta.limite %></td>
    <td><%= conta.vencimento %></td>
    <td><%= link_to 'Show', conta %></td>
    <td><%= link_to 'Edit', edit_conta_path(conta) %></td>
    <td><%= link_to 'Destroy', conta, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Conta', new_conta_path %>

app/views/contas/new.html.erb
<h1>New conta</h1>

<%= render 'form' %>

<%= link_to 'Back', contas_path %>

app/views/contas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @conta.nome %>
</p>

<p>
  <b>Numero:</b>
  <%= @conta.numero %>
</p>

<p>
  <b>Agencia:</b>
  <%= @conta.agencia %>
</p>

<p>
  <b>Descricao:</b>
  <%= @conta.descricao %>
</p>

<p>
  <b>Tipo:</b>
  <%= @conta.tipo %>
</p>

<p>
  <b>Juros:</b>
  <%= @conta.juros %>
</p>

<p>
  <b>Saldo:</b>
  <%= @conta.saldo %>
</p>

<p>
  <b>Limite:</b>
  <%= @conta.limite %>
</p>

<p>
  <b>Vencimento:</b>
  <%= @conta.vencimento %>
</p>


<%= link_to 'Edit', edit_conta_path(@conta) %> |
<%= link_to 'Back', contas_path %>