config/routes.rb
ControleFinanceiro::Application.routes.draw do
  resources :sub_categorias

  resources :categorias

  resources :transacoes

  resources :contas

end

app/controllers/transacoes_controller.rb
class TransacoesController < ApplicationController
  # GET /transacoes
  # GET /transacoes.json
  def index
    @transacoes = Transacao.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transacoes }
    end
  end

  # GET /transacoes/1
  # GET /transacoes/1.json
  def show
    @transacao = Transacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transacao }
    end
  end

  # GET /transacoes/new
  # GET /transacoes/new.json
  def new
    @transacao = Transacao.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transacao }
    end
  end

  # GET /transacoes/1/edit
  def edit
    @transacao = Transacao.find(params[:id])
  end

  # POST /transacoes
  # POST /transacoes.json
  def create
    @transacao = Transacao.new(params[:transacao])

    respond_to do |format|
      if @transacao.save
        format.html { redirect_to @transacao, notice: 'Transacao was successfully created.' }
        format.json { render json: @transacao, status: :created, location: @transacao }
      else
        format.html { render action: "new" }
        format.json { render json: @transacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transacoes/1
  # PUT /transacoes/1.json
  def update
    @transacao = Transacao.find(params[:id])

    respond_to do |format|
      if @transacao.update_attributes(params[:transacao])
        format.html { redirect_to @transacao, notice: 'Transacao was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transacoes/1
  # DELETE /transacoes/1.json
  def destroy
    @transacao = Transacao.find(params[:id])
    @transacao.destroy

    respond_to do |format|
      format.html { redirect_to transacoes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/transacoes_helper.rb
module TransacoesHelper
end

app/views/transacoes/_form.html.erb
<%= form_for(@transacao) do |f| %>
  <% if @transacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transacao.errors.count, "error") %> prohibited this transacao from being saved:</h2>

      <ul>
      <% @transacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :valor %><br />
    <%= f.text_field :valor %>
  </div>
  <div class="field">
    <%= f.label :pago %><br />
    <%= f.check_box :pago %>
  </div>
  <div class="field">
    <%= f.label :comprovante %><br />
    <%= f.text_field :comprovante %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :vencimento %><br />
    <%= f.date_select :vencimento %>
  </div>
  <div class="field">
    <%= f.label :pagamento %><br />
    <%= f.date_select :pagamento %>
  </div>
  <div class="field">
    <%= f.label :frequencia %><br />
    <%= f.text_field :frequencia %>
  </div>
  <div class="field">
    <%= f.label :conta %><br />
    <%= f.text_field :conta %>
  </div>
  <div class="field">
    <%= f.label :sub_categoria %><br />
    <%= f.text_field :sub_categoria %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transacoes/edit.html.erb
<h1>Editing transacao</h1>

<%= render 'form' %>

<%= link_to 'Show', @transacao %> |
<%= link_to 'Back', transacoes_path %>

app/views/transacoes/index.html.erb
<h1>Listing transacoes</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Tipo</th>
    <th>Valor</th>
    <th>Pago</th>
    <th>Comprovante</th>
    <th>Data</th>
    <th>Vencimento</th>
    <th>Pagamento</th>
    <th>Frequencia</th>
    <th>Conta</th>
    <th>Sub categoria</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transacoes.each do |transacao| %>
  <tr>
    <td><%= transacao.nome %></td>
    <td><%= transacao.tipo %></td>
    <td><%= transacao.valor %></td>
    <td><%= transacao.pago %></td>
    <td><%= transacao.comprovante %></td>
    <td><%= transacao.data %></td>
    <td><%= transacao.vencimento %></td>
    <td><%= transacao.pagamento %></td>
    <td><%= transacao.frequencia %></td>
    <td><%= transacao.conta %></td>
    <td><%= transacao.sub_categoria %></td>
    <td><%= link_to 'Show', transacao %></td>
    <td><%= link_to 'Edit', edit_transacao_path(transacao) %></td>
    <td><%= link_to 'Destroy', transacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transacao', new_transacao_path %>

app/views/transacoes/new.html.erb
<h1>New transacao</h1>

<%= render 'form' %>

<%= link_to 'Back', transacoes_path %>

app/views/transacoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @transacao.nome %>
</p>

<p>
  <b>Tipo:</b>
  <%= @transacao.tipo %>
</p>

<p>
  <b>Valor:</b>
  <%= @transacao.valor %>
</p>

<p>
  <b>Pago:</b>
  <%= @transacao.pago %>
</p>

<p>
  <b>Comprovante:</b>
  <%= @transacao.comprovante %>
</p>

<p>
  <b>Data:</b>
  <%= @transacao.data %>
</p>

<p>
  <b>Vencimento:</b>
  <%= @transacao.vencimento %>
</p>

<p>
  <b>Pagamento:</b>
  <%= @transacao.pagamento %>
</p>

<p>
  <b>Frequencia:</b>
  <%= @transacao.frequencia %>
</p>

<p>
  <b>Conta:</b>
  <%= @transacao.conta %>
</p>

<p>
  <b>Sub categoria:</b>
  <%= @transacao.sub_categoria %>
</p>


<%= link_to 'Edit', edit_transacao_path(@transacao) %> |
<%= link_to 'Back', transacoes_path %>