config/routes.rb
ControleFinanceiro::Application.routes.draw do
  resources :sub_categorias

  resources :categorias

  resources :transacoes

  resources :contas

end

app/models/sub_categoria.rb
class SubCategoria < ActiveRecord::Base
  belongs_to :categoria
  attr_accessible :descricao, :nome
end

app/controllers/sub_categorias_controller.rb
class SubCategoriasController < ApplicationController
  # GET /sub_categorias
  # GET /sub_categorias.json
  def index
    @sub_categorias = SubCategoria.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sub_categorias }
    end
  end

  # GET /sub_categorias/1
  # GET /sub_categorias/1.json
  def show
    @sub_categoria = SubCategoria.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sub_categoria }
    end
  end

  # GET /sub_categorias/new
  # GET /sub_categorias/new.json
  def new
    @sub_categoria = SubCategoria.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sub_categoria }
    end
  end

  # GET /sub_categorias/1/edit
  def edit
    @sub_categoria = SubCategoria.find(params[:id])
  end

  # POST /sub_categorias
  # POST /sub_categorias.json
  def create
    @sub_categoria = SubCategoria.new(params[:sub_categoria])

    respond_to do |format|
      if @sub_categoria.save
        format.html { redirect_to @sub_categoria, notice: 'Sub categoria was successfully created.' }
        format.json { render json: @sub_categoria, status: :created, location: @sub_categoria }
      else
        format.html { render action: "new" }
        format.json { render json: @sub_categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sub_categorias/1
  # PUT /sub_categorias/1.json
  def update
    @sub_categoria = SubCategoria.find(params[:id])

    respond_to do |format|
      if @sub_categoria.update_attributes(params[:sub_categoria])
        format.html { redirect_to @sub_categoria, notice: 'Sub categoria was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sub_categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categorias/1
  # DELETE /sub_categorias/1.json
  def destroy
    @sub_categoria = SubCategoria.find(params[:id])
    @sub_categoria.destroy

    respond_to do |format|
      format.html { redirect_to sub_categorias_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/subcategorias_helper.rb
module SubcategoriasHelper
end

app/views/sub_categorias/_form.html.erb
<%= form_for(@sub_categoria) do |f| %>
  <% if @sub_categoria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub_categoria.errors.count, "error") %> prohibited this sub_categoria from being saved:</h2>

      <ul>
      <% @sub_categoria.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br />
    <%= f.text_field :categoria %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_categorias/edit.html.erb
<h1>Editing sub_categoria</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub_categoria %> |
<%= link_to 'Back', sub_categorias_path %>

app/views/sub_categorias/index.html.erb
<h1>Listing sub_categorias</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Descricao</th>
    <th>Categoria</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sub_categorias.each do |sub_categoria| %>
  <tr>
    <td><%= sub_categoria.nome %></td>
    <td><%= sub_categoria.descricao %></td>
    <td><%= sub_categoria.categoria %></td>
    <td><%= link_to 'Show', sub_categoria %></td>
    <td><%= link_to 'Edit', edit_sub_categoria_path(sub_categoria) %></td>
    <td><%= link_to 'Destroy', sub_categoria, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sub categoria', new_sub_categoria_path %>

app/views/sub_categorias/new.html.erb
<h1>New sub_categoria</h1>

<%= render 'form' %>

<%= link_to 'Back', sub_categorias_path %>

app/views/sub_categorias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @sub_categoria.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%= @sub_categoria.descricao %>
</p>

<p>
  <b>Categoria:</b>
  <%= @sub_categoria.categoria %>
</p>


<%= link_to 'Edit', edit_sub_categoria_path(@sub_categoria) %> |
<%= link_to 'Back', sub_categorias_path %>